theme = "catppuccin_mocha"

[editor]
line-number = "relative"
undercurl = true
true-color = true
# end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"

[keys.normal]
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"

# [editor.inline-diagnostics]
# cursor-line = "hint"
# other-lines = "disable"

[editor.lsp]
display-inlay-hints = true
