#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

mon_con=$(xrandr --query | grep " connected" | cut -d" " -f1)
mon_arr=($mon_con)
mon_len=${#mon_arr[@]}
mon_primary=$(xrandr | grep "primary" | cut -d" " -f1) 

for m in ${mon_arr[@]}; do
    if [ $m != $mon_primary ]; then
        mon_secondary+=$m
    fi
done

if [ $mon_len -eq 1 ]; then
    bspc monitor ${mon_arr[0]} -d 1 2 3 4 5 6 7 8 9 10
elif [ $mon_len -eq 2 ]; then
    bspc monitor $mon_primary -d 1 2 3 4 5
    bspc monitor ${mon_secondary[0]} -d 6 7 8 9 10
fi

$HOME/.config/polybar/launch.sh
#bspc monitor HDMI-0 -d II IV VI VIII X
#bspc monitor DVI-D-0 -d I III V VII IX

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

bspc rule -a Thunderbird desktop='^10'
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

thunderbird &
